services:
  fiap-orch-sales:
    build: .
    container_name: fiap-orch-sales
    command: uvicorn src.main:app --host 0.0.0.0 --port 8004 --reload
    ports:
      - "8004:8004"
    environment:
      - BUYERS_BASE_URL=http://localhost:8002
      - VEHICLES_BASE_URL=http://localhost:8000
      - PAYMENTS_BASE_URL=http://localhost:8003
      - KEYCLOAK_BASE_URL=http://localhost:8080
      - KEYCLOAK_REALM=fiap-realm
      - KEYCLOAK_CLIENT_ID=fiap-orch-sales
      - KEYCLOAK_CLIENT_SECRET=super-secret
      - HTTP_TIMEOUT_SECS=10

